---
- name: Patching APT based packages
  apt: upgrade=dist update_cache=yes
  when: ansible_os_family == "Debian"
  notify: restart system

- name: Patching YUM based packages
  yum: name=* state=latest disablerepo= "{{ repo_name }}" exclude="{{ansible_local.pkgexclude.exclude_pkg}}"
  when: ansible_os_family == "RedHat"
  notify: restart system

#- name: Removing ZYPPER custom repositories
#  zypper_repository: name= "{{ repo_name }}" state=absent
#  when: ansible_os_family == "Suse"

- name: Patching ZYPPER based packages
  zypper: name=* state=latest 
  when: ansible_os_family == "Suse"
  notify: restart system

